server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:xgfulijun/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
eureka:
  client:
    service-url:
      defaultZone:  http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/

